name: Test and Release

on:
  push:
    branches: ['**']

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test-and-release:
    name: Test and Release
    runs-on: ubuntu-latest

    steps:
      # Setup the node environment
      - name: Setup node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 20.4.0
          cache: 'yarn'

      # Checks out latest code
      - name: Checkout
        uses: actions/checkout@v3.1.0

      # Install all dependencies
      - name: Install deps
        run: yarn install --immutable

      # Build our packages
      - name: Build packages
        run: yarn -r build

      # Test our packages
      - name: Test packages
        run: yarn -r test

      # Use Changesets to create a release pull request or publish to npm
      - name: Create Release Pull Request or Publish to npm
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
